routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');

Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'index', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/gioi-thieu-cong-ty', ['as' => 'introduce.company', 'uses' => 'DefaultController@index']);
    Route::get('/cac-hoat-dong-ngoai-khoa', ['as' => 'activities', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/lien-he', ['as' => 'contact', 'uses' => 'ContactController@index']);
    Route::post('/lien-he', ['as' => 'contact.post', 'uses' => 'ContactController@store']);

    Route::get('/goc-tu-van', ['as' => 'consultation.index', 'uses' => 'ConsultationController@index']);
    Route::get('/du-hoc-han-quoc', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@korean_study_abroad']);
    Route::get('/du-hoc-nhat-ban', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@japan_study_abroad']);
    Route::get('/thuc-tap-sinh', ['as' => 'apprentice.index', 'uses' => 'DefaultController@apprentice']);
    Route::get('/ky-su', ['as' => 'engineer.index', 'uses' => 'DefaultController@engineer']);
    Route::get('/ky-su-co-khi', ['as' => 'engineer.mechanical.index', 'uses' => 'DefaultController@engineer_mechanical']);
    Route::get('/ky-su/{slug}.{id}', ['as' => 'engineer.mechanical.view', 'uses' => 'OrderController@view']);

    Route::get('/post', ['as' => 'post', 'uses' => 'PostController@index']);
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Backend',
    'middleware' => ['auth', 'admin'],
    'as'        => 'admin.'
], function () {
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'home.index', 'uses' => 'DefaultController@index']);
    Route::resource('permissions', 'PermissionsController');
    Route::resource('roles', 'RolesController');
    Route::get('/media', ['as' => 'media.index', 'uses' => 'MediaController@index']);

    Route::group([
        'as' => 'common.',
        'prefix' => 'common'
    ], function(){
        Route::get('/getLangJs', ['as' => 'getLangJs', 'uses' => 'CommonController@getLangJs']);
        Route::post('/setActive', ['as' => 'setActive', 'uses' => 'CommonController@setActive']);
        Route::post('/setHighlight', ['as' => 'setHighlight', 'uses' => 'CommonController@setHighlight']);
    });

    Route::group([
        'prefix'    => 'users',
        'as'        => 'users.',
        '_active_menu' => 'users'
    ], function(){
        Route::get('/', ['as' => 'index', 'uses' => 'UserController@index', '_active_menu' => 'index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('/{id}', ['as' => 'profile', 'uses' => 'UserController@profile']);
        Route::patch('/{id}/update', ['as' => 'profile.update', 'uses' => 'UserController@updateProfile']);
        Route::delete('/{id}/destroy', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
        Route::post('/password/update', ['as' => 'password.update', 'uses' => 'UserController@updatePassword']);
    });

    //Post Category
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/delete/multi', ['as' => 'categories.delete.multi', 'uses' => 'CategoryController@deleteMulti']);

    //Catalogue Order
    Route::resource('catalogues', 'CatalogueController');
    Route::post('/catalogues/delete/multi', ['as' => 'catalogues.delete.multi', 'uses' => 'CatalogueController@deleteMulti']);

    //Post
    Route::post('/posts/delete/multi', ['as' => 'posts.delete.multi', 'uses' => 'PostController@deleteMulti']);
    Route::resource('posts', 'PostController');

    //Order
    Route::post('/orders/delete/multi', ['as' => 'orders.delete.multi', 'uses' => 'OrderController@deleteMulti']);
    Route::resource('orders', 'OrderController');

    //Tag
    Route::resource('tags', 'TagController');
    Route::post('/tags/delete/multi', ['as' => 'tags.delete.multi', 'uses' => 'TagController@deleteMulti']);

    //Support
    Route::resource('supports', 'SupportController');
    Route::post('/supports/delete/multi', ['as' => 'supports.delete.multi', 'uses' => 'SupportController@deleteMulti']);

    //Setting
    Route::group([
        'prefix'    => 'settings',
        'as'        => 'settings.'
    ], function(){
        Route::get('/general', ['as' => 'general.index', 'uses' => 'SettingController@general']);
        Route::post('/general', ['as' => 'general.update', 'uses' => 'SettingController@updateGeneral']);
        Route::get('/slider', ['as' => 'slider.index', 'uses' => 'SliderController@index']);
        Route::get('/slider/create', ['as' => 'slider.create', 'uses' => 'SliderController@create']);
        Route::post('/slider/create', ['as' => 'slider.store', 'uses' => 'SliderController@store']);
        Route::get('/slider/{id}/edit', ['as' => 'slider.edit', 'uses' => 'SliderController@edit']);
        Route::put('/slider/{id}', ['as' => 'slider.update', 'uses' => 'SliderController@update']);
        Route::delete('/slider/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@delete']);
        Route::post('/slider/delete/multi', ['as' => 'slider.delete.multi', 'uses' => 'SliderController@deleteMulti']);
    });
});

app/Http/Controllers/Backend/TagController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Eloquent\Tag;
use App\Helpers\AppUtil;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TagController extends Controller
{
    /**
     * Show the tag management page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Tag::paginate(AppUtil::COMMON_PAGINATION);

        return view('backend.pages.tags.index', [
            'items' => $items
        ]);
    }

    /**
     * Show the tag create page.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.tags.create');
    }

    /**
     * Create post category info
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'name' => 'required'
        ], [
            'name.required' => trans('common.validation.required', ["atribute" => "tên"])
        ]);

        if ($validator->fails()) {
            flash($validator->errors()->first(), 'error');
            return redirect()->back();
        }

        Tag::create($data);

        flash(trans('backend/common.data.update.success'), 'success');
        return redirect(route('admin.tags.index'));
    }

    /**
     * Show the tag edit page.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Tag::find($id);

        if ($item) {
            return view('backend.pages.tags.edit', [
                'item' => $item
            ]);
        } else {
            flash("Dữ liệu không tồn tại !", 'error');
            return view('backend.errors.404');
        }
    }

    /**
     * Update Tag info
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $cat = Tag::findOrFail($id);
        $data = $request->all();

        $validator = Validator::make($data, [
            'name' => 'required'
        ], [
            'name.required' => trans('common.validation.required', ["atribute" => "tên"])
        ]);

        if ($validator->fails()) {
            flash($validator->errors()->first(), 'error');
            return redirect()->back();
        }

        $cat->fill($data)->save();

        flash(trans('backend/common.data.update.success'), 'success');
        return redirect(route('admin.tags.index'));
    }

    /**
     * Delete specific Tag.
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $cat = Tag::find($id);

        if ($cat) {
            $cat->delete();
            flash(trans('backend/common.data.update.success'), 'success');
            return redirect()->back();
        }
    }

    /**
     * Delete Multi Post Catgory
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function deleteMulti(Request $request)
    {
        $data_ids = explode(',', $request->data_ids);

        if (count($data_ids) && $request->isMethod('post'))
        {
            Tag::destroy($data_ids);

            flash(trans('backend/common.data.update.success'), 'success');
            return redirect()->back();
        }
    }
}

resources/views/backend/pages/tags/create.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Quản lý thẻ tag</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Quản lý thẻ tag</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.tags.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Thêm mới</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin thẻ tag</h5>
                    </div>
                    <div class="ibox-content">
                        <form id="app-tag" class="form-horizontal form-label-left"
                              action="{{ route('admin.tags.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên thẻ tag
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="name" required="required"
                                           class="form-control" name="name" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Mô tả
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                        <textarea id="description" class="form-control" name="description"
                                                  rows="5"></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                    <a href="{{ route('admin.tags.index') }}"><button type="button" class="btn btn-danger">Huỷ</button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/tags/edit.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Quản lý thẻ tag</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Quản lý thẻ tag</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.tags.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Chỉnh sửa</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin thẻ tag</h5>
                    </div>
                    <div class="ibox-content">
                        <form id="app-tag" class="form-horizontal form-label-left" action="{{ route('admin.tags.update', $item->id) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field("PUT") }}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên thẻ tag
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="name" required="required"
                                           class="form-control" name="name" value="{{ $item->name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Mô tả
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                        <textarea id="description" class="form-control" name="description"
                                                  rows="5">{{ $item->description }}</textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                    <a href="{{ route('admin.tags.index') }}"><button type="button" class="btn btn-danger">Huỷ</button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/tags/index.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Danh mục tag</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>Quản lý tag</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.tags.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Danh sách</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Danh sách</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table__management tbl-post-category">
                                <thead>
                                <tr>
                                    <th>
                                        <input class="i-checks check-all" type="checkbox">
                                    </th>
                                    <th> #</th>
                                    <th> Tên</th>
                                    <th> Mô tả</th>
                                    <th> Slug</th>
                                    <th> Count</th>
                                    <th> Trạng thái</th>
                                    <th> @lang('backend/table.common.updated_at') </th>
                                    <th><span class="nobr"> @lang('backend/table.common.action') </span></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($items as $key => $item)
                                    <tr class="even pointer" data-id="{{ $item->id }}" data-model="Tag">
                                        <td><input type="checkbox" class="i-checks input_record" name="records[]"></td>
                                        <td>
                                            {{ ($items->currentPage() - 1) * $items->perPage() + $key + 1 }}
                                        </td>
                                        <td><a href="{{ route('admin.tags.edit', $item->id) }}"> {{ $item->name }} </a></td>
                                        <td> {{ str_limit($item->description, 100) }} </td>
                                        <td> {{ $item->slug }} </td>
                                        <td> 0 </td>
                                        <td class="tbl__btn-status">
                                            <input class="btn-tbl-status" type="checkbox" name="status"
                                                   {{ $item->status == AppUtil::STATUS_ACTIVE ? "checked" : "" }} data-toggle="toggle"
                                                   data-size="mini" data-on="Active" data-off="Blocked"
                                                   data-onstyle="primary" data-offstyle="danger"/>
                                        </td>
                                        <td> {{ $item->updated_at->diffForHumans() }} </td>
                                        <td>
                                            <a href="{{ route('admin.tags.edit', $item->id) }}"
                                               class="btn btn-info btn-xs tbl__btn-edit" title="Chi tiết"><i
                                                        class="fa fa-edit"></i></a>
                                            <form action="{{ route('admin.tags.destroy', $item->id) }}"
                                                  method="post"
                                                  class="tbl__frm-delete" style="display: inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <a class="btn btn-danger btn-xs tbl__btn-delete"><i
                                                            class="fa fa-trash"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="tbl-footer">
                            <div class="tbl-footer--left">
                                <form class="tbl__frm-delete--multi" action="{{ route('admin.tags.delete.multi') }}"
                                      style="display: inline;" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="data_ids" value="" class="data_ids">
                                    <button type="button" class="btn btn-danger btn-sm tbl__btn-delete--multi">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                <a href="{{ route('admin.tags.create') }}">
                                    <button class="btn btn-primary btn-sm tbl__btn-add">
                                        <i class="fa fa-plus"></i> @lang('backend/table.common.add_new')
                                    </button>
                                </a>
                            </div>
                            <div class="pagination-container pull-right no-margin">
                                {{ $items->links('vendor.pagination.custom') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection