routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');

Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'index', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/gioi-thieu-cong-ty', ['as' => 'introduce.company', 'uses' => 'DefaultController@index']);
    Route::get('/cac-hoat-dong-ngoai-khoa', ['as' => 'activities', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/lien-he', ['as' => 'contact', 'uses' => 'ContactController@index']);
    Route::post('/lien-he', ['as' => 'contact.post', 'uses' => 'ContactController@store']);

    Route::get('/goc-tu-van', ['as' => 'consultation.index', 'uses' => 'ConsultationController@index']);
    Route::get('/du-hoc-han-quoc', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@korean_study_abroad']);
    Route::get('/du-hoc-nhat-ban', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@japan_study_abroad']);
    Route::get('/thuc-tap-sinh', ['as' => 'apprentice.index', 'uses' => 'DefaultController@apprentice']);
    Route::get('/ky-su', ['as' => 'engineer.index', 'uses' => 'DefaultController@engineer']);
    Route::get('/ky-su-co-khi', ['as' => 'engineer.mechanical.index', 'uses' => 'DefaultController@engineer_mechanical']);
    Route::get('/ky-su/{slug}.{id}', ['as' => 'engineer.mechanical.view', 'uses' => 'OrderController@view']);

    Route::get('/post', ['as' => 'post', 'uses' => 'PostController@index']);
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Backend',
    'middleware' => ['auth', 'admin'],
    'as'        => 'admin.'
], function () {
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'home.index', 'uses' => 'DefaultController@index']);
    Route::resource('permissions', 'PermissionsController');
    Route::resource('roles', 'RolesController');
    Route::get('/media', ['as' => 'media.index', 'uses' => 'MediaController@index']);

    Route::group([
        'as' => 'common.',
        'prefix' => 'common'
    ], function(){
        Route::get('/getLangJs', ['as' => 'getLangJs', 'uses' => 'CommonController@getLangJs']);
        Route::post('/setActive', ['as' => 'setActive', 'uses' => 'CommonController@setActive']);
        Route::post('/setHighlight', ['as' => 'setHighlight', 'uses' => 'CommonController@setHighlight']);
    });

    Route::group([
        'prefix'    => 'users',
        'as'        => 'users.',
        '_active_menu' => 'users'
    ], function(){
        Route::get('/', ['as' => 'index', 'uses' => 'UserController@index', '_active_menu' => 'index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('/{id}', ['as' => 'profile', 'uses' => 'UserController@profile']);
        Route::patch('/{id}/update', ['as' => 'profile.update', 'uses' => 'UserController@updateProfile']);
        Route::delete('/{id}/destroy', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
        Route::post('/password/update', ['as' => 'password.update', 'uses' => 'UserController@updatePassword']);
    });

    //Post Category
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/delete/multi', ['as' => 'categories.delete.multi', 'uses' => 'CategoryController@deleteMulti']);

    //Catalogue Order
    Route::resource('catalogues', 'CatalogueController');
    Route::post('/catalogues/delete/multi', ['as' => 'catalogues.delete.multi', 'uses' => 'CatalogueController@deleteMulti']);

    //Post
    Route::post('/posts/delete/multi', ['as' => 'posts.delete.multi', 'uses' => 'PostController@deleteMulti']);
    Route::resource('posts', 'PostController');

    //Order
    Route::post('/orders/delete/multi', ['as' => 'orders.delete.multi', 'uses' => 'OrderController@deleteMulti']);
    Route::resource('orders', 'OrderController');

    //Tag
    Route::resource('tags', 'TagController');
    Route::post('/tags/delete/multi', ['as' => 'tags.delete.multi', 'uses' => 'TagController@deleteMulti']);

    //Support
    Route::resource('supports', 'SupportController');
    Route::post('/supports/delete/multi', ['as' => 'supports.delete.multi', 'uses' => 'SupportController@deleteMulti']);

    //Setting
    Route::group([
        'prefix'    => 'settings',
        'as'        => 'settings.'
    ], function(){
        Route::get('/general', ['as' => 'general.index', 'uses' => 'SettingController@general']);
        Route::post('/general', ['as' => 'general.update', 'uses' => 'SettingController@updateGeneral']);
        Route::get('/slider', ['as' => 'slider.index', 'uses' => 'SliderController@index']);
        Route::get('/slider/create', ['as' => 'slider.create', 'uses' => 'SliderController@create']);
        Route::post('/slider/create', ['as' => 'slider.store', 'uses' => 'SliderController@store']);
        Route::get('/slider/{id}/edit', ['as' => 'slider.edit', 'uses' => 'SliderController@edit']);
        Route::put('/slider/{id}', ['as' => 'slider.update', 'uses' => 'SliderController@update']);
        Route::delete('/slider/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@delete']);
        Route::post('/slider/delete/multi', ['as' => 'slider.delete.multi', 'uses' => 'SliderController@deleteMulti']);
    });
});

app/Http/Controllers/Backend/CatalogueController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Eloquent\Catalogue;
use App\Helpers\AppUtil;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CatalogueController extends Controller
{
    /**
     * Show the post category management page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Catalogue::paginate(AppUtil::COMMON_PAGINATION);

        return view('backend.pages.recruits.catalogues.index', [
            'categories' => $categories
        ]);
    }

    /**
     * Delete specific post category.
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $cat = Catalogue::find($id);

        if ($cat) {
            $cat->delete();
            flash(trans('backend/common.data.update.success'), 'success');
            return redirect()->back();
        }
    }

    /**
     * Delete Multi Post Catgory
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function deleteMulti(Request $request)
    {
        $data_ids = explode(',', $request->data_ids);

        if (count($data_ids) && $request->isMethod('post')) {
            foreach ($data_ids as $id) {
                $item = Catalogue::find($id);
                $item->delete();
            }

            flash(trans('backend/common.data.update.success'), 'success');
            return redirect()->back();
        }
    }

    /**
     * Show the post category edit page.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cat = Catalogue::find($id);

        if ($cat) {
            return view('backend.pages.recruits.catalogues.edit', [
                'cat' => $cat
            ]);
        } else {
            flash("Dữ liệu không tồn tại !", 'error');
            return view('backend.errors.404');
        }
    }

    /**
     * Update post category info
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $cat = Catalogue::findOrFail($id);
        $data = $request->all();

        $validator = Validator::make($data, [
            'name_vi' => 'required'
        ], [
            'name_vi.required' => trans('validation.required', ["atribute" => "tên"])
        ]);

        if ($validator->fails()) {
            flash($validator->errors()->first(), 'error');
            return redirect()->back();
        }

        $cat->fill($data)->save();

        flash(trans('backend/common.data.update.success'), 'success');
        return redirect(route('admin.catalogues.index'));
    }

    /**
     * Show the post category create page.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.recruits.catalogues.create');
    }

    /**
     * Create post category info
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'name_vi' => 'required'
        ], [
            'name_vi.required' => trans('validation.required', ["atribute" => "tên"])
        ]);

        if ($validator->fails()) {
            flash($validator->errors()->first(), 'error');
            return redirect()->back();
        }

        Catalogue::create($data);

        flash(trans('backend/common.data.update.success'), 'success');
        return redirect(route('admin.catalogues.index'));
    }
}

resources/views/backend/pages/recruits/catalogues/create.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Quản lý danh mục</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Quản lý danh mục</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.catalogues.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Thêm mới</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin danh mục</h5>
                        <div class="pull-right">
                            <div id="language-group" class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle btn--language" data-toggle="dropdown" aria-expanded="false">
                                    <span class="language--span">Vietnamese</span>
                                    <i class="caret"></i>
                                </button>
                                <ul class="dropdown-menu pull-right language-list" role="menu">
                                    <li data-lang="vi" class="lang--option active"><a href="#">Vietnamese</a></li>
                                    <li data-lang="ja" class="lang--option"><a href="#">Japanese</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form id="hhv-post-category" class="form-horizontal form-label-left"
                              action="{{ route('admin.catalogues.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên danh mục
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text"
                                           class="form-control input-language" data-lang="vi" name="name_vi" value="">
                                    <input type="text"
                                           class="form-control input-language hidden" data-lang="ja" name="name_ja" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Mô tả
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea class="form-control input-language" name="description_vi" data-lang="vi"
                                                  rows="5"></textarea>
                                    <textarea class="form-control input-language hidden" name="description_ja" data-lang="ja"
                                              rows="5"></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                    <a href="{{ route('admin.catalogues.index') }}"><button type="button" class="btn btn-danger">Huỷ</button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/recruits/catalogues/edit.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Quản lý danh mục</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Quản lý danh mục</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.catalogues.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Chỉnh sửa</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin danh mục</h5>
                        <div class="pull-right">
                            <div id="language-group" class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle btn--language" data-toggle="dropdown" aria-expanded="false">
                                    <span class="language--span">Vietnamese</span>
                                    <i class="caret"></i>
                                </button>
                                <ul class="dropdown-menu pull-right language-list" role="menu">
                                    <li data-lang="vi" class="lang--option active"><a href="#">Vietnamese</a></li>
                                    <li data-lang="ja" class="lang--option"><a href="#">Japanese</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form id="hhv-post-category" class="form-horizontal form-label-left" action="{{ route('admin.catalogues.update', $cat->id) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field("PUT") }}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên danh mục
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control input-language" name="name_vi" data-lang="vi" value="{{ $cat->name_vi }}">
                                    <input type="text" class="form-control input-language hidden" name="name_ja" data-lang="ja" value="{{ $cat->name_ja }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Mô tả
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                        <textarea class="form-control input-language" name="description_vi" data-lang="vi" rows="5">{{ $cat->description_vi }}</textarea>
                                        <textarea class="form-control input-language hidden" name="description_ja" data-lang="ja" rows="5">{{ $cat->description_ja }}</textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                    <a href="{{ route('admin.catalogues.index') }}"><button type="button" class="btn btn-danger">Huỷ</button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/recruits/catalogues/index.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Danh mục tin tức</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>Quản lý danh mục</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.orders.index") }}">Danh mục</a>
                </li>
                <li class="active">
                    <strong>Danh sách</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin danh mục</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table__management tbl-post-category">
                                <thead>
                                <tr>
                                    <th>
                                        <input class="i-checks check-all" type="checkbox">
                                    </th>
                                    <th> #</th>
                                    <th> Tên
                                    </th>
                                    <th> Mô tả
                                    </th>
                                    <th> Trạng thái
                                    </th>
                                    <th> @lang('backend/table.common.updated_at') </th>
                                    <th><span class="nobr"> @lang('backend/table.common.action') </span></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $key => $cat)
                                    <tr class="even pointer" data-id="{{ $cat->id }}" data-model="Catalogue">
                                        <td><input type="checkbox" class="i-checks input_record" name="records[]"></td>
                                        <td>
                                            {{ ($categories->currentPage() - 1) * $categories->perPage() + $key + 1 }}
                                        </td>
                                        <td><a href="{{ route('admin.catalogues.edit', $cat->id) }}"> {{ $cat->name_vi }} </a></td>
                                        <td> {{ str_limit($cat->description_vi, 100) }} </td>
                                        <td class="tbl__btn-status">
                                            <input class="btn-tbl-status" type="checkbox" name="status"
                                                   {{ $cat->status == AppUtil::STATUS_ACTIVE ? "checked" : "" }} data-toggle="toggle"
                                                   data-size="mini" data-on="Active" data-off="Blocked"
                                                   data-onstyle="primary" data-offstyle="danger"/>
                                        </td>
                                        <td> {{ $cat->updated_at->diffForHumans() }} </td>
                                        <td>
                                            <a href="{{ route('admin.catalogues.edit', $cat->id) }}"
                                               class="btn btn-info btn-xs tbl__btn-edit" title="Chi tiết"><i
                                                        class="fa fa-edit"></i></a>
                                            <form action="{{ route('admin.catalogues.destroy', $cat->id) }}"
                                                  method="post"
                                                  class="tbl__frm-delete" style="display: inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <a class="btn btn-danger btn-xs tbl__btn-delete"><i
                                                            class="fa fa-trash"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="tbl-footer">
                            <div class="tbl-footer--left">
                                <form class="tbl__frm-delete--multi" action="{{ route('admin.catalogues.delete.multi') }}"
                                      style="display: inline;" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="data_ids" value="" class="data_ids">
                                    <button type="button" class="btn btn-danger btn-sm tbl__btn-delete--multi">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                <a href="{{ route('admin.catalogues.create') }}">
                                    <button class="btn btn-primary btn-sm tbl__btn-add">
                                        <i class="fa fa-plus"></i> @lang('backend/table.common.add_new')
                                    </button>
                                </a>
                            </div>
                            <div class="pagination-container pull-right no-margin">
                                {{ $categories->links('vendor.pagination.custom') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection