routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');

Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'index', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/gioi-thieu-cong-ty', ['as' => 'introduce.company', 'uses' => 'DefaultController@index']);
    Route::get('/cac-hoat-dong-ngoai-khoa', ['as' => 'activities', 'uses' => 'DefaultController@index']);

    Route::get('/gioi-thieu', ['as' => 'introduce', 'uses' => 'DefaultController@index']);
    Route::get('/lien-he', ['as' => 'contact', 'uses' => 'ContactController@index']);
    Route::post('/lien-he', ['as' => 'contact.post', 'uses' => 'ContactController@store']);

    Route::get('/goc-tu-van', ['as' => 'consultation.index', 'uses' => 'ConsultationController@index']);
    Route::get('/du-hoc-han-quoc', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@korean_study_abroad']);
    Route::get('/du-hoc-nhat-ban', ['as' => 'korean.study.abroad.index', 'uses' => 'DefaultController@japan_study_abroad']);
    Route::get('/thuc-tap-sinh', ['as' => 'apprentice.index', 'uses' => 'DefaultController@apprentice']);
    Route::get('/ky-su', ['as' => 'engineer.index', 'uses' => 'DefaultController@engineer']);
    Route::get('/ky-su-co-khi', ['as' => 'engineer.mechanical.index', 'uses' => 'DefaultController@engineer_mechanical']);
    Route::get('/ky-su/{slug}.{id}', ['as' => 'engineer.mechanical.view', 'uses' => 'OrderController@view']);

    Route::get('/post', ['as' => 'post', 'uses' => 'PostController@index']);
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Backend',
    'middleware' => ['auth', 'admin'],
    'as'        => 'admin.'
], function () {
    Route::get('404',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);
    Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);

    Route::get('/', ['as' => 'home.index', 'uses' => 'DefaultController@index']);
    Route::resource('permissions', 'PermissionsController');
    Route::resource('roles', 'RolesController');
    Route::get('/media', ['as' => 'media.index', 'uses' => 'MediaController@index']);

    Route::group([
        'as' => 'common.',
        'prefix' => 'common'
    ], function(){
        Route::get('/getLangJs', ['as' => 'getLangJs', 'uses' => 'CommonController@getLangJs']);
        Route::post('/setActive', ['as' => 'setActive', 'uses' => 'CommonController@setActive']);
        Route::post('/setHighlight', ['as' => 'setHighlight', 'uses' => 'CommonController@setHighlight']);
    });

    Route::group([
        'prefix'    => 'users',
        'as'        => 'users.',
        '_active_menu' => 'users'
    ], function(){
        Route::get('/', ['as' => 'index', 'uses' => 'UserController@index', '_active_menu' => 'index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('/store', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('/{id}', ['as' => 'profile', 'uses' => 'UserController@profile']);
        Route::patch('/{id}/update', ['as' => 'profile.update', 'uses' => 'UserController@updateProfile']);
        Route::delete('/{id}/destroy', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
        Route::post('/password/update', ['as' => 'password.update', 'uses' => 'UserController@updatePassword']);
    });

    //Post Category
    Route::resource('categories', 'CategoryController');
    Route::post('/categories/delete/multi', ['as' => 'categories.delete.multi', 'uses' => 'CategoryController@deleteMulti']);

    //Catalogue Order
    Route::resource('catalogues', 'CatalogueController');
    Route::post('/catalogues/delete/multi', ['as' => 'catalogues.delete.multi', 'uses' => 'CatalogueController@deleteMulti']);

    //Post
    Route::post('/posts/delete/multi', ['as' => 'posts.delete.multi', 'uses' => 'PostController@deleteMulti']);
    Route::resource('posts', 'PostController');

    //Order
    Route::post('/orders/delete/multi', ['as' => 'orders.delete.multi', 'uses' => 'OrderController@deleteMulti']);
    Route::resource('orders', 'OrderController');

    //Tag
    Route::resource('tags', 'TagController');
    Route::post('/tags/delete/multi', ['as' => 'tags.delete.multi', 'uses' => 'TagController@deleteMulti']);

    //Support
    Route::resource('supports', 'SupportController');
    Route::post('/supports/delete/multi', ['as' => 'supports.delete.multi', 'uses' => 'SupportController@deleteMulti']);

    //Setting
    Route::group([
        'prefix'    => 'settings',
        'as'        => 'settings.'
    ], function(){
        Route::get('/general', ['as' => 'general.index', 'uses' => 'SettingController@general']);
        Route::post('/general', ['as' => 'general.update', 'uses' => 'SettingController@updateGeneral']);
        Route::get('/slider', ['as' => 'slider.index', 'uses' => 'SliderController@index']);
        Route::get('/slider/create', ['as' => 'slider.create', 'uses' => 'SliderController@create']);
        Route::post('/slider/create', ['as' => 'slider.store', 'uses' => 'SliderController@store']);
        Route::get('/slider/{id}/edit', ['as' => 'slider.edit', 'uses' => 'SliderController@edit']);
        Route::put('/slider/{id}', ['as' => 'slider.update', 'uses' => 'SliderController@update']);
        Route::delete('/slider/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@delete']);
        Route::post('/slider/delete/multi', ['as' => 'slider.delete.multi', 'uses' => 'SliderController@deleteMulti']);
    });
});

resources/views/backend/pages/recruits/create.blade.php
@extends('backend.layout.default')

@section('scripts')
    <script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
    <script type="text/javascript" src="{{ asset('vendor/ckfinder/ckfinder.js') }}"></script>
    <script src="{{ asset("js/ck.js") }}"></script>

    <script>
        CKEDITOR.replace( 'content_vi' );
        CKEDITOR.replace( 'content_ja' );
        CKEDITOR.replace( 'short_des_vi' );
        CKEDITOR.replace( 'short_des_ja' );
    </script>
@endsection

@section('title_for_layout')
    <title>Quản lý order</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Quản lý order</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="#">Order</a>
                </li>
                <li class="active">
                    <strong>Thêm mới</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin order</h5>
                        <div class="pull-right">
                            <div id="language-group" class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle btn--language" data-toggle="dropdown" aria-expanded="false">
                                    <span class="language--span">Vietnamese</span>
                                    <i class="caret"></i>
                                </button>
                                <ul class="dropdown-menu pull-right language-list" role="menu">
                                    <li data-lang="vi" class="lang--option active"><a href="#">Vietnamese</a></li>
                                    <li data-lang="ja" class="lang--option"><a href="#">Japanese</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form id="app-category" class="form-label-left"
                              action="{{ route('admin.orders.store') }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label class="control-label" for="code">Mã order
                                    <span class="required">*</span>
                                </label>
                                <div class="">
                                    <input type="text" class="form-control" name="code" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name">Tên order
                                    <span class="required">*</span>
                                </label>
                                <div class="">
                                    <input type="text" class="form-control input-language" name="name_vi" data-lang="vi" value="">
                                    <input type="text" class="form-control input-language hidden" name="name_ja" data-lang="ja" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name">Danh mục
                                    <span class="required">*</span>
                                </label>
                                <div class="">
                                    <select class="form-control" name="catalogue_id">
                                        <option value="{{ 0 }}">--Lựa chọn--</option>
                                        @foreach($categories as $cat)
                                            <option value="{{ $cat->id }}">{{ $cat->name_vi }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputImage" class="control-label">
                                    Ảnh minh hoạ</label>
                                <div class="">
                                    <div class="form-group input-group">
                                        <input type="text" id="browseServer-image" name="image" class="form-control"
                                               value="" placeholder="Nhấp chọn ảnh"
                                               onclick="selectFileWithCKFinder('browseServer-image');">
                                        <span class="input-group-btn">
                                        <button class="btn btn-danger" type="button" onclick="delSingleImg(this);"><i
                                                    class="fa fa-minus"></i>
                                        </button>
                                             <button class="btn btn-default" type="button"
                                                     data-target="browseServer-image"
                                                     onclick="showMultiImage(this);"><i class="fa fa-eye"></i>
                                             </button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="video">Video Youtube
                                </label>
                                <div class="">
                                    <input type="text" class="form-control" name="video" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="total">Số lượng
                                </label>
                                <div class="">
                                    <input type="number" class="form-control" name="total" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="content"> Chi tiết Order
                                </label>
                                <div class="input-language" data-lang="vi">
                                    <textarea class="form-control" name="content_vi" rows="5"></textarea>
                                </div>
                                <div class="input-language hidden" data-lang="ja">
                                    <textarea class="form-control" name="content_ja" data-lang="ja" rows="5"></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="short_des">Thông tin bổ sung
                                </label>
                                <div class="input-language" data-lang="vi">
                                        <textarea class="form-control" name="short_des_vi" rows="5"></textarea>
                                </div>
                                <div class="input-language hidden" data-lang="ja">
                                        <textarea class="form-control" name="short_des_ja" rows="5"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="short_des">Hạn nộp hồ sơ
                                </label>

                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control input_date_picker" name="exp_date" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="short_des">Ngày thi
                                </label>
                                <div class="input-group date">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" name="exam_date" class="form-control input_date_picker" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="meta_title">Title Seo</label>
                                <div class="">
                                    <textarea id="meta_title" class="form-control" name="meta_title" rows="3"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="meta_keyword">Meta keyword</label>
                                <div class="">
                                    <textarea id="meta_keyword" class="form-control" name="meta_keyword" rows="3"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="meta_description">Meta description</label>
                                <div class="">
                                    <textarea id="meta_description" class="form-control" name="meta_description" rows="3"></textarea>
                                </div>
                            </div>
                            <div class="form-group" style="padding: 15px 0 25px 0;"><label class="col-xs-1 control-label" style="padding: 0;">Nổi bật</label>
                                <div class="col-sm-11">
                                    <label class="checkbox-inline">
                                        <input type="hidden" name="highlight" value="0" class="highlight--hidden">
                                        <input class="i-checks ckHighlight" type="checkbox" value="1" id="ckHighlight">
                                    </label>
                                    <label class="checkbox-inline"></label>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="">
                                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                                    <a href="{{ route('admin.orders.index') }}"><button type="button" class="btn btn-danger">Huỷ</button></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- My Modal Image -->
    <div id="myModalImage" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <img src="" class="image_preview img-responsive center-block">
            </div>
        </div>
    </div>
@endsection

resources/views/backend/pages/recruits/index.blade.php
@extends('backend.layout.default')

@section('title_for_layout')
    <title>Danh mục Order</title>
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>Quản lý Order</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route("admin.orders.index") }}">Bài viết</a>
                </li>
                <li class="active">
                    <strong>Danh sách</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>Thông tin Order</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <form action="{{ route("admin.orders.index") }}" method="GET">
                                <div class="col-sm-5 m-b-xs">
                                    <select class="input-sm form-control input-s-sm inline" name="catalogue_id">
                                        <option value="0">--Tất cả danh mục--</option>
                                        @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ app('request')->input('catalogue_id') == $category->id ? "selected" : "" }}>{{ $category->name_vi }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-sm-4 m-b-xs">
                                    <div data-toggle="buttons" class="btn-group">
                                        <label class="btn btn-sm btn-white {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_TO_DAY ? "active" : "" }}">
                                            <input type="radio"
                                                   id="day"
                                                   name="time"
                                                   {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_TO_DAY ? "checked" : "" }}
                                                   value="{{ \App\Eloquent\Order::$FILTER_TIME_TYPE_TO_DAY }}"> Day </label>
                                        <label class="btn btn-sm btn-white {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_WEEK ? "active" : "" }}">
                                            <input type="radio"
                                                   id="week"
                                                   name="time"
                                                   {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_WEEK ? "checked" : "" }}
                                                   value="{{ \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_WEEK }}"> Week </label>
                                        <label class="btn btn-sm btn-white {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_MONTH ? "active" : "" }}">
                                            <input type="radio"
                                                   id="month"
                                                   name="time"
                                                   {{ app('request')->input('time') == \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_MONTH ? "checked" : "" }}
                                                   value="{{ \App\Eloquent\Order::$FILTER_TIME_TYPE_THIS_MONTH }}"> Month </label>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="input-group">
                                        <input type="text"
                                               placeholder="Tên"
                                               class="input-sm form-control"
                                               value="{{ app('request')->input('title') }}"
                                               name="title">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-sm btn-primary"> Search</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped table__management tbl-post-category">
                                <thead>
                                <tr>
                                    <th>
                                        <input class="i-checks check-all" type="checkbox">
                                    </th>
                                    <th> #</th>
                                    <th> Tên
                                    </th>
                                    <th> Trạng thái
                                    </th>
                                    <th> @lang('backend/table.common.updated_at') </th>
                                    <th><span class="nobr"> @lang('backend/table.common.action') </span></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($posts as $key => $post)
                                    <tr class="even pointer" data-id="{{ $post->id }}" data-model="Order">
                                        <td><input type="checkbox" class="i-checks input_record" name="records[]"></td>
                                        <td>
                                            {{ ($posts->currentPage() - 1) * $posts->perPage() + $key + 1 }}
                                        </td>
                                        <td><a href="{{ route('admin.orders.edit', $post->id) }}"> {{ $post->name_vi }} </a></td>
                                        <td class="tbl__btn-status">
                                            <input class="btn-tbl-status" type="checkbox" name="status"
                                                   {{ $post->status == AppUtil::STATUS_ACTIVE ? "checked" : "" }} data-toggle="toggle"
                                                   data-size="mini" data-on="Active" data-off="Blocked"
                                                   data-onstyle="primary" data-offstyle="danger"/>
                                        </td>
                                        <td> {{ $post->updated_at->diffForHumans() }} </td>
                                        <td>
                                            <a href="{{ route('admin.orders.edit', $post->id) }}"
                                               class="btn btn-info btn-xs tbl__btn-edit" title="Chi tiết"><i
                                                        class="fa fa-edit"></i></a>
                                            <form action="{{ route('admin.orders.destroy', $post->id) }}"
                                                  method="post"
                                                  class="tbl__frm-delete" style="display: inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <a class="btn btn-danger btn-xs tbl__btn-delete"><i
                                                            class="fa fa-trash"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="tbl-footer">
                            <div class="tbl-footer--left">
                                <form class="tbl__frm-delete--multi" action="{{ route('admin.orders.delete.multi') }}"
                                      style="display: inline;" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="data_ids" value="" class="data_ids">
                                    <button type="button" class="btn btn-danger btn-sm tbl__btn-delete--multi">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                <a href="{{ route('admin.orders.create') }}">
                                    <button class="btn btn-primary btn-sm tbl__btn-add">
                                        <i class="fa fa-plus"></i> @lang('backend/table.common.add_new')
                                    </button>
                                </a>
                            </div>
                            <div class="pagination-container pull-right no-margin">
                                {{ $posts->links('vendor.pagination.custom') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection